gpu: "2"
multi_gpu: null


model_name: model_difflow
iters: 4

# grad_clip #################

full: False

arch: PointConvLightRes
last_relu: False
allow_less_points: False

# general args
batch_size: 4
epochs: 1060
learning_rate: 0.001

optimizer: AdamW
pretrain: ./pretrain_weights/model_difflow_355_0.0114.pth
#pretrain: null
weight_decay: 0.0001
  
dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: FlyingThings3DSubset 
val_dataset: FlyingThings3DSubset # KITTI 
data_root: /dataset
val_path: /dataset

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 16


# uncertainty
uncertainty: 0.02






